# -*- coding: utf-8 -*-
"""CIE2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WF9TTYuvPkp8TIIcDTWv4fKo-9bYxtBz
"""

import numpy as np
import pandas as pd
df=pd.read_csv('titanic.csv')
print(df)

df.describe()

df.info()

df.duplicated().sum()

df['Age'].unique()

# @title Central tendencyof Fare
Fare_mean=df['Fare'].mean
Fare_median=df['Fare'].median
Fare_mode=df['Fare'].mode
print("mean of Fare:",Fare_mean)
print("median of Fare:",Fare_median)
print("mode of Fare:",Fare_mode)

# @title Find the null values and fill new data with mean
import numpy as np
import matplotlib.pyplot as plt
import seaborn  as sns
df=pd.read_csv('titanic.csv')
df['Survived'].replace({0: 'not Survived',1: 'Survived'})['inplace=0']
survived_counts=df['Survived'].value_counts
sns.countplot(x='Survived',hue='pclass' data=df)
plt.grld()
plt.show()
df.head(10)