# -*- coding: utf-8 -*-
"""CIE3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B3Y8a_qtLerpS2C0v52XQfetoVZor88g
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
data=pd.read_csv('/content/housing.csv')

print(data.head())

print(data.isnull().sum)

print(data.describe())

import pandas as pd
from sklearn model_selection import train_test_splitting
from sklearn datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy
iris=load_iris()
x=iris.data()
u