# -*- coding: utf-8 -*-
"""CIE4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CEi0PEsEWyqkh1xvnFobm4s4e6NGh1CM
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

data=pd.read_csv("/content/Mall_Customers.csv")
x=data.iloc[:,[3,4]].values

wc=[]
for i in range(1,11):
  k_means=KMeans(n_clusters=i,init="k-means++",random_state=42)
  k_means.fit(x)
  wc.append(k_means.inertia_)

plt.plot(range(1,11),wc)
plt.title("the enblow of method")
plt.xlabel("number of cluster")
plt.ylabel("wc")
plt.show()